FROM python:3

COPY main.py /main.py

RUN pip install --upgrade pip \
    && pip install confluent_kafka redis flask fastapi uvicorn

EXPOSE 5050

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5050"]
