FROM python:3

COPY post_producer.py /post_producer.py

RUN pip install --upgrade pip \
    && pip install confluent_kafka redis flask fastapi uvicorn

EXPOSE 5050

CMD ["uvicorn", "post_producer:app", "--host", "0.0.0.0", "--port", "5050"]
