version: "3.3"

services:
  app-server1:
    build:
      context: ./get 
    networks:
      - mybridge

  app-server2:
    build:
      context: ./post 
    ports:
      - "5050:5050"
    networks:
      - mybridge

  my-redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mybridge

networks:
  mybridge:
    driver: bridge
