version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest  
    container_name: ZOOKEEPER
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    restart: always

  kafka:
    image: bitnami/kafka:latest  
    hostname: kafka
    container_name: KAFKA
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: INTERNAL://:9090,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9090,EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
    restart: always
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 1

  kowl:
    image: quay.io/cloudhut/kowl
    container_name: KOWL
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      kafka:
        restart: true
        condition: service_healthy

volumes:
  zookeeper_data:
    driver: data
  kafka_data:
    driver: data
